export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: 'PHPNuxBill',
      description: ' PHPNuxBill offers a comprehensive solution for managing user authentication, billing, and network resources. Its user-friendly interface ensures effortless navigation, while its robust features guarantee optimal performance and reliability. Embrace the future of ISP billing with PHPNuxBill, where innovation meets simplicity.',
      ogImage: '/hero.png',
      ogImageComponent: 'PhpnuxBillOgImage',
      ogImageColor: 'light',
      umami: {
        enable: true,
        src: 'https://cloud.umami.is/script.js',
        dataWebsiteId: '39b92e6c-9b98-4e25-b4a7-1d2fb022305f',
      },
    },
    theme: {
      customizable: true,
      color: 'zinc',
      radius: 0.5,
    },
    banner: {
      enable: true,
      showClose: false,
      content: 'PHPNuxBill Ultimate is out!',
      to: 'https://phpnuxbill.org/ultimate',
      target: '_blank',
      border: true,
    },
    header: {
      title: 'PHPNuxBill',
      showTitle: true,
      logo: {
        light: '/logo.png',
        dark: '/logo.png',
      },
      border: false,
      darkModeToggle: true,
      languageSwitcher: {
        enable: true,
        triggerType: 'icon',
        dropdownType: 'select',
      },
      nav: [{
        title: 'Home',
        to: '/',
        target: '_self',
        showLinkIcon: false,
      }, {
        title: 'Documentation',
        to: '/getting-started/introduction',
        target: '_self',
        showLinkIcon: false,
      }, {
        title: 'Extensions',
        links: [{
          title: 'Themes',
          to: '/extensions/themes',
          description: 'Get the best of PHPNuxBill with beautiful themes',
          icon: 'lucide:palette',
        }, {
          title: 'Plugins',
          to: '/extensions/plugins',
          description: 'Explore available plugins and extensions.',
          icon: 'lucide:box',
        }, {
          title: 'Payment Gateways',
          to: '/extensions/payment-gateways',
          description: 'Check out available payment gateways',
          target: '_self',
          icon: 'lucide:credit-card',
          }, {
            title: 'Devices',
            to: '/extensions/devices',
            description: 'Check out available device plugins',
            target: '_self',
            icon: 'lucide:cpu',
          }],
      },
      {
        title: 'Community',
        links: [{
          title: 'Telegram',
          to: 'https://t.me/phpnuxbill',
          target: '_blank',
          icon: 'lucide:send',
        }, {
          title: 'Facebook',
          to: 'https://web.facebook.com/groups/1404570750225597/?ref=share',
          target: '_blank',
          icon: 'lucide:facebook',
        }, {
          title: 'Forum',
          to: 'https://github.com/orgs/hotspotbilling/discussions',
          target: '_blank',
          icon: 'lucide:github',
        }],
      },
      {
        title: 'Support',
        to: '/support',
        target: '_self',
        showLinkIcon: false,
      }, {
        title: 'Credits',
        links: [{
          title: 'Bootstrap V3',
          to: 'https://getbootstrap.com/docs/3.4/',
          target: '_blank',
        }, {
          title: 'Admin LTE V3',
          to: 'https://adminlte.io/docs/3.2/',
          target: '_blank',
        }, {
          title: 'Smarty Template V4',
          to: 'https://www.smarty.net/',
          target: '_blank',
        }, {
          title: 'PHP IdiORM',
          to: 'https://www.php-idiorm.com/',
          target: '_blank',
        }, {
          title: 'PHP mPDF',
          to: 'https://mpdf.github.io/',
          target: '_blank',
        }, {
          title: 'PHP QRCode',
          to: 'http://phpqrcode.sourceforge.net/',
          target: '_blank',
        }, {
          title: 'PHP Net_RouterOS',
          to: 'https://github.com/pear2/Net_RouterOS',
          target: '_blank',
        }, {
          title: 'Summernote',
          to: 'https://summernote.org/',
          target: '_blank',
        }, {
          title: 'PHP Mailer',
          to: 'https://github.com/PHPMailer/PHPMailer',
          target: '_blank',
        }, {
          title: 'FreeRadius',
          to: 'https://freeradius.org/',
          target: '_blank',
        }, {
          title: 'Shadcn Docs',
          to: 'https://github.com/ZTL-UwU/shadcn-docs-nuxt',
          target: '_blank',
        }],
      },],
      links: [
        {
          icon: 'lucide:heart',
          to: 'https://t.me/phpnuxbill',
          target: '_blank',
        },
        {
          icon: 'lucide:github',
          to: 'https://github.com/hotspotbilling/phpnuxbill',
          target: '_blank',
        },
      ],
    },
    aside: {
      useLevel: true,
      levelStyle: 'aside',
      collapse: false,
      collapseLevel: 1,
      folderStyle: 'default',
    },
    main: {
      padded: true,
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: false,
      codeCopyIcon: 'lucide:clipboard',
      editLink: {
        enable: true,
        pattern: 'https://github.com/hotspotbilling/phpnuxbill.org/edit/main/content/:path',
        text: 'Edit this page',
        icon: 'lucide:square-pen',
        placement: ['docsFooter'],
      },
      backToTop: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'css': 'vscode-icons:file-type-css',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-light-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
      },
    },
    footer: {
      border: true,
      credits: 'All Right Reserved © 2024',
      links: [
        {
          icon: 'lucide:heart',
          title: 'Donate',
          to: '',
          target: '_blank',
        },
        {
          icon: 'lucide:send',
          to: 'https://t.me/phpnuxbill',
          target: '_blank',
        },
        {
          icon: 'lucide:facebook',
          to: 'https://web.facebook.com/groups/1404570750225597/?ref=share',
          target: '_blank',
        },
        {
          icon: 'lucide:youtube',
          to: '',
          target: '_blank',
        },
        {
          icon: 'lucide:github',
          to: 'https://github.com/orgs/hotspotbilling/discussions',
          target: '_blank',
        },
      ],
    },
    toc: {
      enable: true,
      enableInMobile: true,
      enableInHomepage: false,
      title: 'On this page',
      links: [
        {
          title: 'Star on GitHub',
          icon: 'lucide:star',
          to: 'https://github.com/hotspotbilling/phpnuxbill',
          target: '_blank',
          showLinkIcon: true,
        },
        {
          title: 'Create Issues',
          icon: 'lucide:circle-dot',
          to: 'https://github.com/hotspotbilling/phpnuxbill/issues',
          target: '_blank',
          showLinkIcon: true,
        },
      ],
      iconLinks: [
        {
          icon: 'lucide:coffee',
          to: 'https://www.paypal.com/paypalme/ibnux',
          target: '_blank',
        },
        {
          icon: 'lucide:send',
          to: 'https://t.me/phpnuxbill',
          target: '_blank',
        },
        {
          icon: 'lucide:facebook',
          to: 'https://web.facebook.com/groups/1404570750225597/?ref=share',
          target: '_blank',
        },
        {
          icon: 'lucide:messages-square',
          to: 'https://github.com/hotspotbilling/phpnuxbill/discussions',
          target: '_blank',
        },
      ],
      carbonAds: {
        enable: false,
        disableInDev: true,
        disableInMobile: false,
        fallback: false,
        fallbackMessage: 'Please support us by disabling your ad blocker.',
        code:  'CEBIEK3N',
        placement: 'phpnuxbillorg',
        format: 'cover',
      },
    },
    search: {
      enable: true,
      inAside: false,
      style: 'input',
    },
    data: {},
  },
});